Portere til kotlin
navikt/dokgen pull request #143
Opened 2020-10-12 09:03 UTC by MengZhuNAV

test github scripts

2020-10-12 13:34 UTC, hensol requested changes
Hei,
Har du testet at denne fungerer sammen med malene i familie-ba-dokgen?

2020-10-12 13:34 UTC, hensol commented on pom.xml
> +            <groupId>org.json</groupId>
Hva er grunnen til at vi trenger denne?

2020-10-12 13:34 UTC, hensol commented on pom.xml
> +                        <plugin>jpa</plugin>
Trenger vel ikke jpa her.

2020-10-12 13:34 UTC, hensol commented on src/main/kotlin/no/nav/dokgen/configuration/DelayedShutdownHook.kt
> +            e.printStackTrace()
better to use a logger.

2020-10-12 14:28 UTC, henninghaakonsen submitted a review, later dismissed
I have not looked at the implementation in detail, but it looks good 👍

2020-10-13 07:53 UTC, MengZhuNAV commented on pom.xml
> +            <groupId>org.json</groupId>
We dont actually need it. Removed!

2020-10-13 07:53 UTC, MengZhuNAV commented on pom.xml
> +                        <plugin>jpa</plugin>
True, removed!

2020-10-13 07:53 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/dokgen/configuration/DelayedShutdownHook.kt
> +            e.printStackTrace()
Agree and changed!

2020-10-13 08:00 UTC, hensol approved these changes

2020-10-13 08:08 UTC, merged